# ═══════════════════════════════════════════════════════════════════════
#  RACZ - Idle
#  Created by Congrak - Rodrigo Celis
# ═══════════════════════════════════════════════════════════════════════

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_wayland_inhibit = true
}

listener {
    timeout = 300
    on-timeout = ~/.config/hypr/scripts/smart-lock
}

listener {
    timeout = 500
    on-timeout = systemctl suspend
}
